<?php

/**
 * Implements hook_cron().
 */
 
function hello_cron() {
	 \Drupal::messenger()->addMessage(t('Hello CRON'));

}

/**
 * Implements hook_user_login().
 */
function hello_user_login($account) {
	$name = $account->getDisplayName();
	\Drupal::messenger()->addMessage(t('Welcome ').$name);
	
	/*$roles = \Drupal::config('hello.settings')->get('user_statistics_roles');
	$user_roles = $account->getAccount()->getRoles();;
	$diff = array_intersect($roles, $user_roles);
	if (count($diff)>'0'){ */
		$database = \Drupal::database();
		$database->insert('hello_user_statistics')
		  ->fields([
				'uid' => $account->id(),
				'action' => '1',
				'time' => REQUEST_TIME,
				])
		  ->execute();
	//}

}

/**
 * Implements hook_user_logout().
 */
function hello_user_logout($account){
	$database = \Drupal::database();
	$database->insert('hello_user_statistics')
	  ->fields([
			'uid' => $account->id(),
			'action' => '0',
			'time' => REQUEST_TIME,
			])
	  ->execute();
}
